### ISSUE TITLE
docker-compose with traefik

### ISSUE THREAD

**Issue by CaosFR** [BenjaminPrice/fvtt-docker#22]
Hi,

According to your tutorial (https://benprice.dev/posts/fvtt-docker-tutorial/) I have modify this "docker-compose.yaml" for easy update with a script. Can you tell me if it's correct and if I will have some trouble with Portainer (I have already create foundry with Portainer) ? If I understood correctly, the entry point  "/opt/foundryvtt/run-server.sh" is in the DockerFile ?

$ nano docker-compose.yaml
```
version: '3'
services:
  foundryvtt:
    image: direckthit/fvtt-docker:latest
    container_name: fvtt
    restart: unless-stopped
    ports: 
      - 30000:30000
    volumes:
      - /home/roleplay/foundrydata:/data/foundryvtt
      - /home/roleplay/foundrydl:/host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foundryvtt.entrypoints=http"
      - "traefik.http.routers.foundryvtt.rule=Host(`foundry.rp.fr`)"
      - "traefik.http.middlewares.foundryvtt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.foundryvtt.middlewares=foundryvtt-https-redirect"
      - "traefik.http.routers.foundryvtt-secure.entrypoints=https"
      - "traefik.http.routers.foundryvtt-secure.rule=Host(`foundry.rp.fr`)"
      - "traefik.http.routers.foundryvtt-secure.tls=true"
      - "traefik.http.routers.foundryvtt-secure.tls.certresolver=http"
      - "traefik.http.routers.foundryvtt-secure.service=foundryvtt"
      - "traefik.http.services.foundryvtt.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

```
-------------------------
If someone is intersting with my update script see below.
$ nano dockerUpdate.sh
```
#!/bin/sh
echo "--- MAJ des images ---"
docker-compose -f /home/roleplay/fail2ban/docker-compose.yml pull
docker-compose -f /home/roleplay/portainer/docker-compose.yaml pull
docker-compose -f /home/roleplay/traefik/docker-compose.yaml pull
docker-compose -f /home/roleplay/foundrydl/docker-compose.yaml pull
cd /home/roleplay/jitsi/
docker-compose pull
echo "--- Reboot des contenaires ---"
docker-compose -f /home/roleplay/fail2ban/docker-compose.yml up -d --remove-orphans
docker-compose -f /home/roleplay/portainer/docker-compose.yaml up -d --remove-orphans
docker-compose -f /home/roleplay/traefik/docker-compose.yaml up -d --remove-orphans
docker-compose -f /home/roleplay/foundrydl/docker-compose.yaml up -d --remove-orphans
cd /home/roleplay/jitsi/
docker-compose up -d --remove-orphans
echo "--- Supression des anciennes images ---"
docker image prune -f
echo "--- Visualisation des images ---"
docker images
echo "--- Visualisation des contenaires ---"
docker ps -a
```

Thanks
